# Generated by Django 6.0 on 2025-12-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "ticker",
                    models.CharField(max_length=30, unique=True, verbose_name="Ticker"),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[("nse", "NSE"), ("bse", "BSE")],
                        max_length=3,
                        verbose_name="Exchange",
                    ),
                ),
                ("sector", models.CharField(max_length=50, verbose_name="Sector")),
                ("listing_date", models.DateField(verbose_name="Listing Date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active?"),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MetricCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PNL", "Profit & Loss"),
                            ("BS", "Balance Sheet"),
                            ("CF", "Cash Flow"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Category Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric Category",
                "verbose_name_plural": "Metric Categories",
            },
        ),
        migrations.CreateModel(
            name="CompanyFundamental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "operating_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "net_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "roce",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "debt_to_equity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sales_cagr_5y",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "profit_cagr_5y",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundamentals",
                        to="stocks.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyMarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "pe",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "pb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market",
                        to="stocks.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Metric Code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "formula",
                    models.TextField(blank=True, null=True, verbose_name="Formula"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metrics",
                        to="stocks.metriccategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField(verbose_name="Year")),
                (
                    "quarter",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Quarter"
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("annual", "Annual"), ("quarterly", "Quarterly")],
                        max_length=10,
                        verbose_name="Period Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Period",
                "verbose_name_plural": "Time Periods",
                "ordering": ["-year", "-quarter"],
                "unique_together": {("year", "quarter", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="FinancialValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="Value",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="stocks.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="stocks.metric",
                        verbose_name="Metric",
                    ),
                ),
                (
                    "time_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="stocks.timeperiod",
                        verbose_name="Time Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Value",
                "verbose_name_plural": "Financial Values",
                "indexes": [
                    models.Index(
                        fields=["company", "metric", "time_period"],
                        name="stocks_fina_company_81d3a6_idx",
                    )
                ],
                "unique_together": {("company", "metric", "time_period")},
            },
        ),
    ]
