# Generated by Django 6.0 on 2025-12-15 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyfundamental",
            name="net_profit",
        ),
    ]
