# Generated by Django 6.0 on 2025-12-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_companyfundamental_net_profit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfundamental',
            options={'verbose_name': 'Company Fundamental', 'verbose_name_plural': 'Company Fundamentals'},
        ),
    ]
