# Generated by Django 6.0 on 2025-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_companyfundamental_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymarketsnapshot',
            options={'verbose_name': 'Market Snapshot', 'verbose_name_plural': 'Market Snapshots'},
        ),
        migrations.RemoveField(
            model_name='companymarketsnapshot',
            name='dividend_yield',
        ),
        migrations.AddField(
            model_name='companymarketsnapshot',
            name='high_52w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='High'),
        ),
        migrations.AddField(
            model_name='companymarketsnapshot',
            name='low_52w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Low'),
        ),
        migrations.AlterField(
            model_name='companymarketsnapshot',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Market Cap'),
        ),
        migrations.AlterField(
            model_name='companymarketsnapshot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
