# Generated by Django 6.0 on 2025-12-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_companymarketsnapshot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Closing Price')),
                ('volume', models.BigIntegerField(verbose_name='Volume')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stocks.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'CompanyHistory',
                'verbose_name_plural': 'CompanyHistories',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date'], name='stocks_comp_company_549c53_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
