# Generated by Django 6.0 on 2025-12-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_companyhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='listing_date',
        ),
    ]
